# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161005_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='pincode',
            field=models.IntegerField(default=400001),
        ),
    ]
