# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-24 06:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_locality_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 24, 6, 33, 57, 736764, tzinfo=utc)),
        ),
    ]
