# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-24 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170124_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='locality',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
