# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-25 06:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170124_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 25, 6, 47, 51, 745476, tzinfo=utc)),
        ),
    ]
