# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-09 13:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170125_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 9, 13, 32, 1, 229458, tzinfo=utc)),
        ),
    ]
