# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-17 06:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170209_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 17, 6, 25, 45, 311930, tzinfo=utc)),
        ),
    ]
