# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-23 15:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170523_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 23, 15, 33, 16, 840591, tzinfo=utc)),
        ),
    ]
