# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-16 18:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20170617_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 16, 18, 54, 20, 770988, tzinfo=utc)),
        ),
    ]
