# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-09 03:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiftSeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=150)),
                ('description', models.TextField(default='', max_length=250)),
                ('owner_address', models.TextField(default='', max_length=250)),
                ('shop_name', models.CharField(default='', max_length=50)),
                ('shop_pno', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 13 digits allowed.", regex='^\\+?1?\\d{9,12}$')])),
                ('shop_address', models.TextField(default='', max_length=250)),
                ('image', models.ImageField(default='giftseller/default.jpg', upload_to='giftseller/images/')),
                ('GST_number', models.CharField(blank=True, default='', max_length=500)),
                ('mou_signed_on', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Enabled', 'Enabled'), ('Disabled', 'Disabled')], default='Disabled', max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
