# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 17:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message=b"Phone number must be entered in the format: '+999999999'. Up to 13 digits allowed.", regex=b'^\\+?1?\\d{9,12}$')]),
        ),
    ]
