# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20161009_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_cakemporos_baker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_first_time_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='coupon',
            field=models.ManyToManyField(blank=True, default=b'', to='sales.Coupon'),
        ),
    ]
