# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 19:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20161011_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='reward_id',
            field=models.CharField(default=b'ABC', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message=b"Phone number must be entered in the format: '+999999999'. Up to 13 digits allowed.", regex=b'^\\+?1?\\d{9,12}$')]),
        ),
        migrations.AlterUniqueTogether(
            name='useraccount',
            unique_together=set([('id', 'phone', 'reward_id')]),
        ),
    ]
