# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20161012_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
