# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20161110_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='refresh_token',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='access_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
