# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-17 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20161110_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddresses',
            name='user_locality',
            field=models.TextField(default=b''),
        ),
    ]
