# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baker',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baker',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
