# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_locality_pincode'),
        ('bakers', '0002_auto_20161110_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baker',
            name='shop_locality',
        ),
        migrations.AddField(
            model_name='baker',
            name='shop_locality',
            field=models.ManyToManyField(default=b'', to='core.Locality'),
        ),
    ]
