# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-20 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakers', '0003_auto_20161214_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='baker',
            name='description',
            field=models.TextField(default=b'', max_length=250),
        ),
    ]
