# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-23 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170523_2042'),
        ('bakers', '0004_baker_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='baker',
            name='serving_localities',
            field=models.ManyToManyField(default=b'', to='core.Locality'),
        ),
        migrations.RemoveField(
            model_name='baker',
            name='shop_locality',
        ),
        migrations.AddField(
            model_name='baker',
            name='shop_locality',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
