# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-09 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakers', '0005_auto_20170523_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baker',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='baker',
            name='refresh_token',
        ),
    ]
