# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_addon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
