# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20161124_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addon',
            name='quantity',
        ),
        migrations.AddField(
            model_name='addon',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
