# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-25 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20161124_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
