# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-09 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giftsellers', '0001_initial'),
        ('catalog', '0006_addon_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(default=b'products/default.jpg', upload_to=b'addons/images/')),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('status', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftsellers.GiftSeller')),
            ],
        ),
        migrations.AddField(
            model_name='addon',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
