"""
Django settings for cakemporos project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import sys
import urlparse
import dj_database_url
import boto
from boto.s3.key import Key
import boto.s3.connection


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 's%qlyue=z4enmbl3gc+lbqoox905xn_nhd+)ec8pr35fap396h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = (
    #3rd PArty admin
    #'grappelli',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'crispy_forms',
    'storages',
    #My apps
    'accounts',
    'bakers',
    'catalog',
    'cart',
    'core',
    'order',
    'sales',
    'giftsellers',

)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # 'whitenoise.middleware.WhiteNoiseMiddleware',
)

ROOT_URLCONF = 'cakemporos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "django.template.context_processors.media",
                'cart.context_processors.get_cart_items_total',
                'catalog.context_processors.get_product_category',
                'mybaker.context_processors.baker_products',
                'mybaker.context_processors.baker_orders',
                'mybaker.context_processors.baker_sales',
                'mybaker.context_processors.baker_customers',
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
)

WSGI_APPLICATION = 'cakemporos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

urlparse.uses_netloc.append('mysql')
try:

    # Check to make sure DATABASES is set in settings.py file.
    # If not default to {}

    if 'DATABASES' not in locals():
        DATABASES = {}

    if 'mysql://b337cad5e99fd2:ee7f6e90@us-cdbr-iron-east-04.cleardb.net/heroku_9273aa76e71db65' in os.environ:
        url = urlparse.urlparse(os.environ['mysql://b337cad5e99fd2:ee7f6e90@us-cdbr-iron-east-04.cleardb.net/heroku_9273aa76e71db65'])

        # Ensure default database exists.
        DATABASES['default'] = DATABASES.get('default', {})

        # Update with environment configuration.
        DATABASES['default'].update({
            'NAME': 'heroku_9273aa76e71db65',
            'USER': 'b337cad5e99fd2',
            'PASSWORD': 'ee7f6e90',
            'HOST': 'us-cdbr-iron-east-04.cleardb.net',
            'PORT': '3306',
        })
        if self.connection.open:
            self.connection.stat()

        try:
            self.connection = MySQLdb.connect(host='us-cdbr-iron-east-04.cleardb.net',port='3306',db='heroku_9273aa76e71db65',user='b337cad5e99fd2',passwd='ee7f6e90')
        except MySQLdb.OperationalError, e:
            self.connection = None


        if url.scheme == 'mysql':
            DATABASES['default']['ENGINE'] = 'django.db.backends.mysql'
except Exception:
    print 'Unexpected error:', sys.exc_info()

DATABASES['default'] = dj_database_url.config(default='mysql://cakemporos_admin:cecore@127.0.0.1:3306/ce_demo')
DATABASES['default']['OPTIONS'] = {
    'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
}


EMAIL_HOST = 'smtp.gmail.com'
SERVER_EMAIL = 'cakemporos.in@gmail.com'
DEFAULT_FROM_EMAIL = 'cakemporos.in@gmail.com'
EMAIL_NOREPLY_USER = 'no-reply@cakemporos.in'
EMAIL_ORDER_USER = 'orders@cakemporos.in'
EMAIL_SALES_USER = 'sales@cakemporos.in'
EMAIL_CAREER_USER = 'carees@cakemporos.in'
EMAIL_SUPPORT_USER = 'support@cakemporos.in'
EMAIL_ADMIN_USER = 'admin@cakemporos.in'
EMAIL_BILLING_USER = 'billing@cakemporos.in'
EMAIL_HOST_USER = 'cakemporos.in@gmail.com'
EMAIL_HOST_PASSWORD = 'cecore2017'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True

DATETIME_INPUT_FORMATS = (
    '%d/%m/%Y',
    '%d/%m/%y',
    '%y/%m/%d'
    )
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/


'''COMMENT FOR LOCAL SERVER     '''
# STATIC_URL = '/static/'

# STATIC_ROOT = os.path.join(BASE_DIR, "static_src", "static_root")

# MEDIA_URL = '/media/'

# MEDIA_ROOT = os.path.join(BASE_DIR, "static_src", "media_root")

''' TILL HERE '''

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static_src", "our_static"),
    )

#SITE FRAMEWORK
SITE_ID = 1

#CRISPY FORM SETTINGS
CRISPY_TEMPLATE_PACK = 'bootstrap3'

LOGIN_REDIRECT_URL = '/'

SOCIALACCOUNT_QUERY_EMAIL = True

SOCIALACCOUNT_PROVIDERS = {
    'facebook': {
        'SCOPE': ['email', 'publish_stream'],
        'METHOD': 'js_sdk'  # instead of 'oauth2'
    }
}

ACCOUNT_EMAIL_REQUIRED = True

GRAPPELLI_ADMIN_TITLE = "Cakemporos"

DEFAULT_TAX_RATE = 0.05 #1%

DOMAIN_NAME = "www.cakemporos.in"

ADMIN_PHONE_NUMBER = "9766526943"

TWOFACTOR_API_KEY = "eba5c512-7a7a-11e6-a584-00163ef91450"

TRANSACTIONAL_SMS_URL = "http://2factor.in/API/V1/" + TWOFACTOR_API_KEY + "/ADDON_SERVICES/SEND/TSMS"

GOOGLE_API_KEY = "AIzaSyCRcKLBQYizfeHi8fc1GzihE5TK4KTOYEY"
###################################
# s3 storage
###################################

''' COMMENT THIS FOR LIVE SERVER '''
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto.S3BotoStorage'

STATICFILES_STORAGE = 'storages.backends.s3boto.S3BotoStorage'

AWS_S3_HOST = 's3.ap-south-1.amazonaws.com'

AWS_ACCESS_KEY_ID="AKIAID2WI3NWKHO7DOMQ"

AWS_SECRET_ACCESS_KEY="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"

AWS_STORAGE_BUCKET_NAME = 'ce-static-prod'

S3_URL = 'https://%s.s3.amazonaws.com' %AWS_STORAGE_BUCKET_NAME

STATIC_DIRECTORY = '/static/'

MEDIA_DIRECTORY = '/media/'

STATIC_URL = S3_URL + STATIC_DIRECTORY

MEDIA_URL = S3_URL + MEDIA_DIRECTORY

ADMIN_MEDIA_PREFIX = S3_URL + STATIC_DIRECTORY + 'admin/'

AWS_QUERYSTRING_AUTH = False

''' TILL HERE '''