# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        ('catalog', '0001_initial'),
        ('core', '0002_auto_20161005_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Coupon')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Locality')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('weight_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('cupcake_qty_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('egg_or_eggless_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('msg_on_cake', models.TextField(blank=True, default=b'', null=True)),
                ('photo_cake_image', models.ImageField(blank=True, null=True, upload_to=b'cartitem/photocakes/')),
                ('photo_cake_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('cart_item_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('line_total', models.DecimalField(decimal_places=2, default=10.99, max_digits=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cart', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Cart')),
                ('cupcake_qty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.BoxVariations')),
                ('egg_or_eggless', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.EggVariations')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product')),
                ('weight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.WeightVariations')),
            ],
        ),
    ]
