# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20161104_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='taxable_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
    ]
