# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_taxable_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='taxable_total',
            new_name='service_charge_value',
        ),
        migrations.AddField(
            model_name='cart',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
    ]
