# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_addon'),
        ('cart', '0005_auto_20161107_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='addon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Addon'),
        ),
    ]
