# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_cartitem_addon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='addon_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
    ]
