# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20161125_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='addon_qty',
            field=models.IntegerField(default=1),
        ),
    ]
