# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-23 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_cartitem_addon_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
    ]
