# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-23 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_cartitem_delivery_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
    ]
