# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-13 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_remove_cart_cart_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='giftitem_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='giftitem_qty',
            field=models.IntegerField(default=1),
        ),
    ]
