# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 21:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0001_initial'),
        ('bakers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default=b'ABC', max_length=120, unique=True)),
                ('status', models.CharField(choices=[(b'Pending', b'Pending'), (b'Confirmed', b'Confirmed'), (b'Baking', b'Baking'), (b'Shipped', b'Shipped'), (b'Complete', b'Complete'), (b'Cancelled', b'Cancelled')], default=b'Pending', max_length=120)),
                ('sub_total', models.DecimalField(decimal_places=2, default=10.99, max_digits=50)),
                ('discount_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('final_total', models.DecimalField(decimal_places=2, default=10.99, max_digits=50)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('baker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bakers.Baker')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cart.Cart')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_order_id', models.CharField(default=b'ABC12', max_length=120, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.ManyToManyField(default=b'', to='order.Order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'user',
            },
        ),
        migrations.CreateModel(
            name='OrderShippingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.CharField(default=b'', max_length=120)),
                ('delivery_time', models.CharField(default=b'', max_length=120)),
                ('shipping_address', models.TextField(default=b'')),
                ('payment_method', models.CharField(default=b'Cash On Delivery', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('main_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.OrderHistory')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
