# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Cart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cartitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.CartItem'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(b'Pending', b'Pending'), (b'Confirmed', b'Confirmed'), (b'Baking', b'Baking'), (b'Shipped', b'Shipped'), (b'Complete', b'Complete'), (b'Cancelled', b'Cancelled'), (b'Ready', b'Ready')], default=b'Pending', max_length=120),
        ),
    ]
