# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20161009_1433'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set([('id', 'order_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='orderhistory',
            unique_together=set([('id', 'main_order_id')]),
        ),
    ]
