# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20161012_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='final_order_total',
            field=models.IntegerField(default=0),
        ),
    ]
