# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orderhistory_final_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='final_order_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
    ]
