# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20161107_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
