# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='approval',
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
