# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20161107_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
