# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 04:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20161112_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordershippingdetails',
            name='order',
        ),
    ]
