# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_remove_ordershippingdetails_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
