# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_order_tracking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='final_order_total',
        ),
    ]
