# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_remove_orderhistory_final_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_clearance',
            field=models.BooleanField(default=False),
        ),
    ]
