# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-18 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_order_payment_clearance'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='final_total',
            field=models.DecimalField(decimal_places=2, default=10.99, max_digits=50),
        ),
    ]
