# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-19 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_orderhistory_final_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='final_total',
        ),
    ]
