# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-09 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_remove_orderhistory_final_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='ask_customer_for_feedback',
            field=models.BooleanField(default=False),
        ),
    ]
