# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-16 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_orderhistory_ask_customer_for_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=b'ABCDE', max_length=120, unique=True),
        ),
    ]
